{
 "title": "🟢 EXP1 - Solar powered node prioritization",
 "tags": [
  "k8s",
  "node",
  "monitoring"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(node_cpu_seconds_total, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU usage of load-testing app",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (node) (rate(container_cpu_usage_seconds_total{pod=~\"load-simulators-deployment.*\", namespace=\"testing\"}[5m]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Battery Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "node_solar_battery_level", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage (Rate, non-idle)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\",instance=~\"$node\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - (sum by (instance) (node_memory_MemAvailable_bytes{instance=~\"$node\"}) / sum by (instance) (node_memory_MemTotal_bytes{instance=~\"$node\"})))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}