{
 "title": "🟢 EXP2 - Node utilization",
 "time": { "from": "2025-04-27T16:13:00.000Z", "to": "2025-04-27T16:40:49.000Z" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(node_cpu_seconds_total, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"testing\", deployment=\"kafka-task-runner\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Battery Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "node_solar_battery_level", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage (Rate, non-idle)",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\",instance=~\"$node\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - (sum by (instance) (node_memory_MemAvailable_bytes{instance=~\"$node\"}) / sum by (instance) (node_memory_MemTotal_bytes{instance=~\"$node\"})))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}