apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-task-runner
  namespace: testing
spec:
  replicas: 0
  selector:
    matchLabels:
      app: kafka-task-runner
  template:
    metadata:
      labels:
        app: kafka-task-runner
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: kafka-task-runner
          image: local/task-runner:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: kafka-task-runner-config
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
