apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: battery-level-simulator-sm
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: battery-level
  namespaceSelector:
    matchNames:
      - simulators
  endpoints:
    - port: http
      path: /metrics
      interval: 10s
